# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QE7DI30meijGtoUJu6KOEMDyTwjxXopQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df=pd.read_csv("/content/student.csv")

df = df.rename(columns={
    # Demographics
    '1. What is your year of study?': 'Year_of_Study',
    '2. What is your gender?': 'Gender',
    '3. How often do you have difficulty falling asleep at night? ': 'Sleep_diff',
    '4. On average, how many hours of sleep do you get on a typical day?': 'Sleep_Hours_Cat',
    '5. How often do you wake up during the night and have trouble falling back asleep?': 'Sleep_back',
    '6. How would you rate the overall quality of your sleep?': 'Sleep_Quality',
    '7. How often do you experience difficulty concentrating during lectures or studying due to lack of sleep?': 'Concentration_Issue',
    '8. How often do you feel fatigued during the day, affecting your ability to study or attend classes?': 'Daytime_Fatigue',
    '9. How often do you miss or skip classes due to sleep-related issues (e.g., insomnia, feeling tired)?': 'Missed_Classes',
    '10. How would you describe the impact of insufficient sleep on your ability to complete assignments and meet deadlines?': 'Assignment_Impact',
    '11. How often do you use electronic devices (e.g., phone, computer) before going to sleep?': 'Device_Usage_Before_Sleep',
    '12. How often do you consume caffeine (coffee, energy drinks) to stay awake or alert?': 'Caffeine_Consumption',
    '13. How often do you engage in physical activity or exercise?': 'Physical_Activity',
    '14. How would you describe your stress levels related to academic workload?': 'Stress_Level_Cat',
    '15. How would you rate your overall academic performance (GPA or grades) in the past semester?': 'Performance_Cat'
})

df.head()

for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].dropna().unique())

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].str.strip()

sleep_diff_map = {
    'Never': 0,
    'Rarely (1-2 times a week)': 1,
    'Sometimes (3-4 times a week)': 2,
    'Often (5-6 times a week)': 3,
    'Every night': 4
}

sleep_hours_map = {
    'Less than 4 hours': 1,
    '4-5 hours': 2,
    '6-7 hours': 3,
    '7-8 hours': 4,
    'More than 8 hours': 5
}

sleep_back_map = {
    'Never': 0,
    'Rarely (1-2 times a week)': 1,
    'Sometimes (3-4 times a week)': 2,
    'Often (5-6 times a week)': 3,
    'Every night': 4
}

sleep_quality_map = {
    'Very poor': 0,
    'Poor': 1,
    'Average': 2,
    'Good': 3,
    'Very good': 4
}

concentration_map = {
    'Never': 0,
    'Rarely': 1,
    'Sometimes': 2,
    'Often': 3,
    'Always': 4
}

fatigue_map = {
    'Never': 0,
    'Rarely': 1,
    'Sometimes': 2,
    'Often': 3,
    'Always': 4
}

missed_classes_map = {
    'Never': 0,
    'Rarely (1-2 times a month)': 1,
    'Sometimes (1-2 times a week)': 2,
    'Often (3-4 times a week)': 3,
    'Always': 4
}

assignment_impact_map = {
    'No impact': 0,
    'Minor impact': 1,
    'Moderate impact': 2,
    'Major impact': 3,
    'Severe impact': 4
}

device_usage_map = {
    'Never': 0,
    'Rarely (1-2 times a week)': 1,
    'Sometimes (3-4 times a week)': 2,
    'Often (5-6 times a week)': 3,
    'Every night': 4
}

caffeine_map = {
    'Never': 0,
    'Rarely (1-2 times a week)': 1,
    'Sometimes (3-4 times a week)': 2,
    'Often (5-6 times a week)': 3,
    'Every day': 4
}

physical_activity_map = {
    'Never': 0,
    'Rarely (1-2 times a week)': 1,
    'Sometimes (3-4 times a week)': 2,
    'Often (5-6 times a week)': 3,
    'Every day': 4
}

stress_map = {
    'No stress': 0,
    'Low stress': 1,
    'High stress': 3,
    'Extremely high stress': 4
}

performance_map = {
    'Poor': 0,
    'Below Average': 1,
    'Average': 2,
    'Good': 3,
    'Excellent': 4
}

df['Sleep_diff'] = df['Sleep_diff'].map(sleep_diff_map)
df['Sleep_Score'] = df['Sleep_Hours_Cat'].map(sleep_hours_map)
df['Sleep_back'] = df['Sleep_back'].map(sleep_back_map)
df['Sleep_Quality'] = df['Sleep_Quality'].map(sleep_quality_map)
df['Concentration_Issue'] = df['Concentration_Issue'].map(concentration_map)
df['Daytime_Fatigue'] = df['Daytime_Fatigue'].map(fatigue_map)
df['Missed_Classes'] = df['Missed_Classes'].map(missed_classes_map)
df['Assignment_Impact'] = df['Assignment_Impact'].map(assignment_impact_map)
df['Device_Usage_Before_Sleep'] = df['Device_Usage_Before_Sleep'].map(device_usage_map)
df['Caffeine_Consumption'] = df['Caffeine_Consumption'].map(caffeine_map)
df['Physical_Activity'] = df['Physical_Activity'].map(physical_activity_map)
df['Stress_Score'] = df['Stress_Level_Cat'].map(stress_map)
df['Performance_Score'] = df['Performance_Cat'].map(performance_map)

print(df[
    [
        'Sleep_diff','Sleep_Score','Sleep_back','Sleep_Quality',
        'Concentration_Issue','Daytime_Fatigue','Missed_Classes',
        'Assignment_Impact','Device_Usage_Before_Sleep',
        'Caffeine_Consumption','Physical_Activity',
        'Stress_Score','Performance_Score'
    ]
].isna().sum())

df.head()

feature_cols = [
    'Sleep_diff',
    'Sleep_Score',
    'Sleep_back',
    'Sleep_Quality',
    'Concentration_Issue',
    'Daytime_Fatigue',
    'Missed_Classes',
    'Assignment_Impact',
    'Device_Usage_Before_Sleep',
    'Caffeine_Consumption',
    'Physical_Activity',
    'Stress_Score'
]

target_col = 'Performance_Score'



df_model = df.dropna(subset=[target_col])

performance_3class = {
    0: 0,  # Poor → Low
    1: 0,  # Below Avg → Low
    2: 1,  # Average → Medium
    3: 2,  # Good → High
    4: 2   # Excellent → High
}

df_model['Performance_3class'] = df_model['Performance_Score'].map(performance_3class)

from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


X = df_model[feature_cols]
y = df_model['Performance_3class']


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=41,
    stratify=y
)

log_reg = LogisticRegression(
                             max_iter=1000,
                              )
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("R² Score:", r2)

tolerance_accuracy = np.mean(np.abs(y_test - y_pred) <= 1)
print("Tolerance Accuracy (±1 class):", tolerance_accuracy)

plt.figure(figsize=(8, 5))
sns.boxplot(
    data=df,
    x='Sleep_Hours_Cat',
    y='Performance_Score',
    palette='viridis'
)

plt.title("Sleep Duration vs Academic Performance")
plt.xlabel("Average Sleep Duration")
plt.ylabel("Performance Score")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 5))
sns.boxplot(
    data=df,
    x='Stress_Level_Cat',
    y='Performance_Score',
    palette='cool'
)

plt.title("Stress Level vs Academic Performance")
plt.xlabel("Stress Level")
plt.ylabel("Performance Score")
plt.tight_layout()
plt.show()

